### ISSUE TITLE
Error: Could not import `.globals`

### ISSUE THREAD

**Issue by synthecypher** [gameclosure/devkit2#106]
Installed as instructed on Docs, checked requirements, tried reinstall global module and still getting this error when trying to use the module cli.

```
C:\Users\Josh\Projects
λ git --version
git version 1.9.4.msysgit.0

C:\Users\Josh\Projects
λ node --version
v0.10.32

C:\Users\Josh\Projects
λ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

C:\Users\Josh\Projects
λ devkit

Error loading module:
     [[ ./globals ]]
     requested by: ./<initial file>
     current directory: C:\Users\Josh\Projects
   Error: Could not import `.globals`
        looked in:
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals.js
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals/index.js
        Import Stack:

      at loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:693:17)
      at ENV_node.loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:462:18)
      at _require (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:856:34)
      at C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:88:27
      at Object.<anonymous> (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src\devkit.js:30:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)

C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:879
          throw err;
                ^
Error: Could not import `.globals`
        looked in:
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals.js
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals/index.js
        Import Stack:

    at loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:693:17)
    at ENV_node.loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:462:18)
    at _require (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:856:34)
    at C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:88:27
    at Object.<anonymous> (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src\devkit.js:30:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by synthecypher** [comment]
For anyone else wondering why they're having this issue it's because DevKit2 doesn't play well with non-unix file systems meaning you'll need to use a Bash prompt such as msys, or cygwin. Git for Windows usually comes with GitBash which should suffice until you run into the second problem which is all the resource calls to the devkit API will be broken due to them using Windows-style file paths.

e.g.

```api?=C:\Users\Guy\Projects\helloworld\resources\failing\to\load.png```

Instead of Unix-style file paths which come up like...

```api?=/home/Projects/helloworld/resources/succeeding/to/load.png```

However after switching to Ubuntu and attempting to run a project again I still had a lot of issues with app specific resources failing to load (maybe because I'm not on a Mac...).

**Comment by jwilm** [comment]
Were you using one of the test projects on ubuntu? The more info you can provide about what you were trying to do, the better chance we have of fixing any issues.
