### ISSUE TITLE
devkit init with git templates no longer works

### ISSUE THREAD

**Issue by collingreen** [gameclosure/devkit2#76]
Reproduce by trying to create a new project using devkit init and a git repository path. The repository is correctly cloned into the src/apps/template/_template folder before the errors start.

`devkit init templatetest --git-template git@github.com:gameclosure/demoGeolocation`

```
Collins-MacBook-Pro:geoloc collingreen$ devkit init --git-template git@github.com:gameclosure/demoGeolocation inittest
[ReferenceError: FatalGitError is not defined]
         [apps]    Creating app using remote template git@github.com:gameclosure/demoGeolocation
          [git]    -> clone --depth 1 git@github.com:gameclosure/demoGeolocation /Users/collingreen/development/devkit2/src/apps/templates/_template
Possibly unhandled TypeError: Cannot read property 'root' of undefined
    at /Users/collingreen/development/devkit2/src/apps/App.js:481:63
    at tryCatch1 (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/promise.js:988:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/Users/collingreen/development/devkit2/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:419:13)
```

**Comment by collingreen** [comment]
Fixed in https://github.com/gameclosure/devkit2/commit/2e2553859ad68e5dbfc98b3346f1fa1acc7e314a
