### ISSUE TITLE
devkit debug native-android throws error

### ISSUE THREAD

**Issue by AnomalyAces** [gameclosure/devkit2#96]
Below are the logs that i recieved when running the the above command
$ devkit debug native-android
        [build]    starting build at Wed Jan 21 2015 16:42:23 GMT-0500 (Eastern Standard Time)
         [apps]    c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\manifest.json
       [module]    browser-mobile
       [module]    c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\modules\devkit-core\src\build\browser
       [module]    browser-desktop
       [module]    c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\modules\devkit-core\src\build\browser
       [module]    native-ios
       [module]    c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\modules\devkit-core\src\build\native\native-ios
       [module]    native-android
       [module]    c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\modules\devkit-core\src\build\native\native-android
       [module]    chrome
       [module]    c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\modules\devkit-core\src\build\chrome

        [build]    Prebuild phase completed for DivineChronicles
        [build]         build for: native-android               scheme: debug

 --- start config ---
                     appPath: c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles
                       debug: true
                      scheme: debug
                      target: native-android
                  schemePath: build\debug
                  outputPath: c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\build\debug\native-android
                jsioPath:
                    jsioPath: c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\build\debug\native-android
                  sdkVersion: 2.0.0
                   isTestApp: undefined
                 isSimulated: undefined
               simulator:
                    deviceId: undefined
                  deviceType: undefined
                        port: undefined
                        port: undefined
                          ip: 192.168.245.134
              localServerURL: 192.168.245.134:9200
                  serverName: local
          outputResourcePath: c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\build\debug\native-android\assets\resources
                      studio: studio.example.com
                     version: debug
                    compress: false
                       appID: 29a3fb1486854fbc810405ce209a7214
              localBuildPath: build\debug\native-android
                    bundleID: com.example.studio.DivineChronicles
                 packageName: com.example.studio.DivineChronicles
                   isAndroid: true
                      repack: false
               enableLogging: false
               resourcesOnly: false
 --- end config ---
 [build-native]    Writing resources for 29a3fb1486854fbc810405ce209a7214 with target native-android
 [jsio-compile]    compiling import devkit.native.launchClient
 [jsio-compile]    jsio_compile "import devkit.native.launchClient" --cwd "c:\\Users\\Jerek\\Desktop\\Game_Development\\GameClosure\\DivineChronicles" --environment "native" --path "[\"c:\\\\Users\\\\Jerek\\\\Desktop\\\\Game_Development\\\\GameClosure\\\\DivineChronicles\\\\modules\\\\devkit-core\\\\node_modules\\\\jsio\\\\packages\",\".\",\"lib\",\"modules\\\\devkit-core\\\\modules\\\\timestep\\\
\src\"]" --includeJsio "true" --appendImport "false" --debug "4" --pathCache "{\"devkit\":\"modules\\\\devkit-core\\\\src\\\\clientapi\",\"ff\":\"modules\\\\devkit-core\\\\src\\\\clientapi\\\\api\\\\ff\",\"squill\":\"modules\\\\devkit-core\\\\modules\\\\squill\"}" --compressorCachePath "build\\debug\\.js-cache-native-android" --defines "{\"BUILD_TARGET\":\"native-android\",\"BUILD_ENV\":\"native\"
,\"DEBUG\":true}" --printOutput  --gcManifest "c:\\Users\\Jerek\\Desktop\\Game_Development\\GameClosure\\DivineChronicles\\manifest.json" --gcDebug "true" --preprocessors "[\"cls\",\"logger\"]"
      [spriter]    spriter --no-clean --cache-file "spritercache-d0b510998a0ba62139515519a378cb27" --scale "1" --dir "c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\resources/" --output "c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\build\debug\native-android\assets\resources\spritesheets" --target "native-android" --binaries "undefined" --is-simulator
"undefined" --spriter-png-fallback "false"
LOG .__imports__ Including native runtime.
     [jvmtools]    connected to localhost:50483
wrote spritesheetSizeMap.json to c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\build\debug\native-android\assets\resources\spritesheets\spritesheetSizeMap.json
[build-browser]    Finished packaging resources
 [build-native]    writing files to c:\Users\Jerek\Desktop\Game_Development\GameClosure\DivineChronicles\build\debug\native-android\assets\resources
wrote manifest.json
wrote native.js
    [ndk-build]    ndk-build -j 8 DEBUG=1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by jwilm** [comment]
It looks like the android ndk was not found on your path. The build failed when running `ndk-build -j8 DEBUG=1`.

**Comment by AnomalyAces** [comment]
I have my android ndk on my path:  C:\Users\[user]\Desktop\Executables\android-ndk-r10d 

is this not the right place for the path or does it need to point to somewhere in the ndk folder?
